server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_management
    username: postgres
    password: Serebro11!!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

card:
  encryption:
    key: ${CARD_ENCRYPTION_KEY:defaultEncryptionKey123}

jwt:
  secret: ${JWT_SECRET:defaultJwtSecretKey1234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours